//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace sigel.Module.BusinessObjects.ORMDataModel1
{

    public partial class CarpetaDetalle : XPObject
    {
        Carpeta fCarpeta;
        public Carpeta Carpeta
        {
            get { return fCarpeta; }
            set { SetPropertyValue<Carpeta>(nameof(Carpeta), ref fCarpeta, value); }
        }
        Instituiciones fInstituicion;
        public Instituiciones Instituicion
        {
            get { return fInstituicion; }
            set { SetPropertyValue<Instituiciones>(nameof(Instituicion), ref fInstituicion, value); }
        }
        DateTime fFechaOperacion;
        public DateTime FechaOperacion
        {
            get { return fFechaOperacion; }
            set { SetPropertyValue<DateTime>(nameof(FechaOperacion), ref fFechaOperacion, value); }
        }
        string fPlazo;
        public string Plazo
        {
            get { return fPlazo; }
            set { SetPropertyValue<string>(nameof(Plazo), ref fPlazo, value); }
        }
        decimal fPagado;
        public decimal Pagado
        {
            get { return fPagado; }
            set { SetPropertyValue<decimal>(nameof(Pagado), ref fPagado, value); }
        }
        string fCuotasVencer;
        public string CuotasVencer
        {
            get { return fCuotasVencer; }
            set { SetPropertyValue<string>(nameof(CuotasVencer), ref fCuotasVencer, value); }
        }
        DateTime fProximoVencimiento;
        public DateTime ProximoVencimiento
        {
            get { return fProximoVencimiento; }
            set { SetPropertyValue<DateTime>(nameof(ProximoVencimiento), ref fProximoVencimiento, value); }
        }
        string fCuota;
        public string Cuota
        {
            get { return fCuota; }
            set { SetPropertyValue<string>(nameof(Cuota), ref fCuota, value); }
        }
        decimal fSaldo;
        public decimal Saldo
        {
            get { return fSaldo; }
            set { SetPropertyValue<decimal>(nameof(Saldo), ref fSaldo, value); }
        }
        string fLinea;
        public string Linea
        {
            get { return fLinea; }
            set { SetPropertyValue<string>(nameof(Linea), ref fLinea, value); }
        }
        string fObservacion;
        public string Observacion
        {
            get { return fObservacion; }
            set { SetPropertyValue<string>(nameof(Observacion), ref fObservacion, value); }
        }
    }

}
