//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace sigel.Module.BusinessObjects.ORMDataModel1
{

    public partial class CarpetaDetalleTarjeta : XPObject
    {
        Carpeta fCarpeta;
        public Carpeta Carpeta
        {
            get { return fCarpeta; }
            set { SetPropertyValue<Carpeta>(nameof(Carpeta), ref fCarpeta, value); }
        }
        Instituiciones fInstituicion;
        public Instituiciones Instituicion
        {
            get { return fInstituicion; }
            set { SetPropertyValue<Instituiciones>(nameof(Instituicion), ref fInstituicion, value); }
        }
        DateTime fFechaEmision;
        public DateTime FechaEmision
        {
            get { return fFechaEmision; }
            set { SetPropertyValue<DateTime>(nameof(FechaEmision), ref fFechaEmision, value); }
        }
        string fTipoDeTarjeta;
        public string TipoDeTarjeta
        {
            get { return fTipoDeTarjeta; }
            set { SetPropertyValue<string>(nameof(TipoDeTarjeta), ref fTipoDeTarjeta, value); }
        }
        decimal fPagoMinimo;
        public decimal PagoMinimo
        {
            get { return fPagoMinimo; }
            set { SetPropertyValue<decimal>(nameof(PagoMinimo), ref fPagoMinimo, value); }
        }
        decimal fDeudaTotal;
        public decimal DeudaTotal
        {
            get { return fDeudaTotal; }
            set { SetPropertyValue<decimal>(nameof(DeudaTotal), ref fDeudaTotal, value); }
        }
        string fObservacion;
        public string Observacion
        {
            get { return fObservacion; }
            set { SetPropertyValue<string>(nameof(Observacion), ref fObservacion, value); }
        }
    }

}
