//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace sigel.Module.BusinessObjects.ORMDataModel1
{

    public partial class Ciudad : XPObject
    {
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        Departamiento fDepartamiento;
        [Association(@"CiudadReferencesDepartamiento")]
        public Departamiento Departamiento
        {
            get { return fDepartamiento; }
            set { SetPropertyValue<Departamiento>(nameof(Departamiento), ref fDepartamiento, value); }
        }
    }

}
