//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace sigel.Module.BusinessObjects.ORMDataModel1
{

    public partial class Departamiento : XPObject
    {
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        Pais fPais;
        [Association(@"DepartamientoReferencesPais")]
        public Pais Pais
        {
            get { return fPais; }
            set { SetPropertyValue<Pais>(nameof(Pais), ref fPais, value); }
        }
        [Association(@"CiudadReferencesDepartamiento"), Aggregated]
        public XPCollection<Ciudad> Ciudades { get { return GetCollection<Ciudad>(nameof(Ciudades)); } }
    }

}
