//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace sigel.Module.BusinessObjects.ORMDataModel1
{

    public partial class GeneralXpObject1 : XPObject
    {
        Socio fSocio;
        public Socio Socio
        {
            get { return fSocio; }
            set { SetPropertyValue<Socio>(nameof(Socio), ref fSocio, value); }
        }
        Instituiciones fInstituicion;
        public Instituiciones Instituicion
        {
            get { return fInstituicion; }
            set { SetPropertyValue<Instituiciones>(nameof(Instituicion), ref fInstituicion, value); }
        }
        DateTime fFechaCreacion;
        public DateTime FechaCreacion
        {
            get { return fFechaCreacion; }
            set { SetPropertyValue<DateTime>(nameof(FechaCreacion), ref fFechaCreacion, value); }
        }
        string fEstado;
        public string Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<string>(nameof(Estado), ref fEstado, value); }
        }
        DateTime fFechaGestion;
        public DateTime FechaGestion
        {
            get { return fFechaGestion; }
            set { SetPropertyValue<DateTime>(nameof(FechaGestion), ref fFechaGestion, value); }
        }
    }

}
