//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace sigel.Module.BusinessObjects.ORMDataModel1
{

    public partial class GestionDetalle : XPObject
    {
        Socio fSocio;
        public Socio Socio
        {
            get { return fSocio; }
            set { SetPropertyValue<Socio>(nameof(Socio), ref fSocio, value); }
        }
        string fEstado;
        public string Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<string>(nameof(Estado), ref fEstado, value); }
        }
        string fComentario;
        public string Comentario
        {
            get { return fComentario; }
            set { SetPropertyValue<string>(nameof(Comentario), ref fComentario, value); }
        }
    }

}
