//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace sigel.Module.BusinessObjects.ORMDataModel1
{

    public partial class Gestion : XPObject
    {
        string fInstituicion;
        public string Instituicion
        {
            get { return fInstituicion; }
            set { SetPropertyValue<string>(nameof(Instituicion), ref fInstituicion, value); }
        }
        string fAsignadoA;
        public string AsignadoA
        {
            get { return fAsignadoA; }
            set { SetPropertyValue<string>(nameof(AsignadoA), ref fAsignadoA, value); }
        }
        DateTime fFechaDeAsignacion;
        public DateTime FechaDeAsignacion
        {
            get { return fFechaDeAsignacion; }
            set { SetPropertyValue<DateTime>(nameof(FechaDeAsignacion), ref fFechaDeAsignacion, value); }
        }
        string fEstado;
        public string Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<string>(nameof(Estado), ref fEstado, value); }
        }
        DateTime fFechaDeTermino;
        public DateTime FechaDeTermino
        {
            get { return fFechaDeTermino; }
            set { SetPropertyValue<DateTime>(nameof(FechaDeTermino), ref fFechaDeTermino, value); }
        }
    }

}
