//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace sigel.Module.BusinessObjects.ORMDataModel1
{

    public partial class Instituiciones : XPObject
    {
        string fRazonSocial;
        public string RazonSocial
        {
            get { return fRazonSocial; }
            set { SetPropertyValue<string>(nameof(RazonSocial), ref fRazonSocial, value); }
        }
        string fNumeroDocumento;
        public string NumeroDocumento
        {
            get { return fNumeroDocumento; }
            set { SetPropertyValue<string>(nameof(NumeroDocumento), ref fNumeroDocumento, value); }
        }
        string fTelefono;
        public string Telefono
        {
            get { return fTelefono; }
            set { SetPropertyValue<string>(nameof(Telefono), ref fTelefono, value); }
        }
    }

}
