//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace sigel.Module.BusinessObjects.ORMDataModel1
{

    public partial class Silo : XPObject
    {
        string fNombre;
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fDepartamiento;
        public string Departamiento
        {
            get { return fDepartamiento; }
            set { SetPropertyValue<string>(nameof(Departamiento), ref fDepartamiento, value); }
        }
        string fCiudad;
        public string Ciudad
        {
            get { return fCiudad; }
            set { SetPropertyValue<string>(nameof(Ciudad), ref fCiudad, value); }
        }
        string fNumeroDeDocumiento;
        public string NumeroDeDocumiento
        {
            get { return fNumeroDeDocumiento; }
            set { SetPropertyValue<string>(nameof(NumeroDeDocumiento), ref fNumeroDeDocumiento, value); }
        }
    }

}
