//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace sigel.Module.BusinessObjects.Gestiones
{

    public partial class GestionMonsanto : XPObject
    {
        string fCargadoPor;
        public string CargadoPor
        {
            get { return fCargadoPor; }
            set { SetPropertyValue<string>(nameof(CargadoPor), ref fCargadoPor, value); }
        }
        string fFechaDeCarga;
        public string FechaDeCarga
        {
            get { return fFechaDeCarga; }
            set { SetPropertyValue<string>(nameof(FechaDeCarga), ref fFechaDeCarga, value); }
        }
        string fEditadoPor;
        public string EditadoPor
        {
            get { return fEditadoPor; }
            set { SetPropertyValue<string>(nameof(EditadoPor), ref fEditadoPor, value); }
        }
        string fFechaEdicion;
        public string FechaEdicion
        {
            get { return fFechaEdicion; }
            set { SetPropertyValue<string>(nameof(FechaEdicion), ref fFechaEdicion, value); }
        }
        string fProductor;
        public string Productor
        {
            get { return fProductor; }
            set { SetPropertyValue<string>(nameof(Productor), ref fProductor, value); }
        }
        string fNombreProductor;
        public string NombreProductor
        {
            get { return fNombreProductor; }
            set { SetPropertyValue<string>(nameof(NombreProductor), ref fNombreProductor, value); }
        }
        string fTipoDocumientoProductor;
        public string TipoDocumientoProductor
        {
            get { return fTipoDocumientoProductor; }
            set { SetPropertyValue<string>(nameof(TipoDocumientoProductor), ref fTipoDocumientoProductor, value); }
        }
        string fNumeroDocumientoProductor;
        public string NumeroDocumientoProductor
        {
            get { return fNumeroDocumientoProductor; }
            set { SetPropertyValue<string>(nameof(NumeroDocumientoProductor), ref fNumeroDocumientoProductor, value); }
        }
        string fTelefonoProductor;
        public string TelefonoProductor
        {
            get { return fTelefonoProductor; }
            set { SetPropertyValue<string>(nameof(TelefonoProductor), ref fTelefonoProductor, value); }
        }
        string fEmailProductor;
        public string EmailProductor
        {
            get { return fEmailProductor; }
            set { SetPropertyValue<string>(nameof(EmailProductor), ref fEmailProductor, value); }
        }
        string fEstanciaProductor;
        public string EstanciaProductor
        {
            get { return fEstanciaProductor; }
            set { SetPropertyValue<string>(nameof(EstanciaProductor), ref fEstanciaProductor, value); }
        }
        string fLocalidadProductor;
        public string LocalidadProductor
        {
            get { return fLocalidadProductor; }
            set { SetPropertyValue<string>(nameof(LocalidadProductor), ref fLocalidadProductor, value); }
        }
        string fDepartamientoProductor;
        public string DepartamientoProductor
        {
            get { return fDepartamientoProductor; }
            set { SetPropertyValue<string>(nameof(DepartamientoProductor), ref fDepartamientoProductor, value); }
        }
        string fHasIntactaCertificada;
        public string HasIntactaCertificada
        {
            get { return fHasIntactaCertificada; }
            set { SetPropertyValue<string>(nameof(HasIntactaCertificada), ref fHasIntactaCertificada, value); }
        }
        string fRindeCertificada;
        public string RindeCertificada
        {
            get { return fRindeCertificada; }
            set { SetPropertyValue<string>(nameof(RindeCertificada), ref fRindeCertificada, value); }
        }
        string fHasIntactaReservaDeGrano;
        public string HasIntactaReservaDeGrano
        {
            get { return fHasIntactaReservaDeGrano; }
            set { SetPropertyValue<string>(nameof(HasIntactaReservaDeGrano), ref fHasIntactaReservaDeGrano, value); }
        }
        string fRindeReservaDeGrano;
        public string RindeReservaDeGrano
        {
            get { return fRindeReservaDeGrano; }
            set { SetPropertyValue<string>(nameof(RindeReservaDeGrano), ref fRindeReservaDeGrano, value); }
        }
        string fSiloEntregaGranoNombre;
        public string SiloEntregaGranoNombre
        {
            get { return fSiloEntregaGranoNombre; }
            set { SetPropertyValue<string>(nameof(SiloEntregaGranoNombre), ref fSiloEntregaGranoNombre, value); }
        }
        string fRazonDeLaLlamada;
        public string RazonDeLaLlamada
        {
            get { return fRazonDeLaLlamada; }
            set { SetPropertyValue<string>(nameof(RazonDeLaLlamada), ref fRazonDeLaLlamada, value); }
        }
        string fComentario;
        public string Comentario
        {
            get { return fComentario; }
            set { SetPropertyValue<string>(nameof(Comentario), ref fComentario, value); }
        }
        string fFechaDeLaCosecha;
        public string FechaDeLaCosecha
        {
            get { return fFechaDeLaCosecha; }
            set { SetPropertyValue<string>(nameof(FechaDeLaCosecha), ref fFechaDeLaCosecha, value); }
        }
        string fMotivoDeLaLlamada;
        public string MotivoDeLaLlamada
        {
            get { return fMotivoDeLaLlamada; }
            set { SetPropertyValue<string>(nameof(MotivoDeLaLlamada), ref fMotivoDeLaLlamada, value); }
        }
        string fTipoDeGestion;
        public string TipoDeGestion
        {
            get { return fTipoDeGestion; }
            set { SetPropertyValue<string>(nameof(TipoDeGestion), ref fTipoDeGestion, value); }
        }
        string fCanal;
        public string Canal
        {
            get { return fCanal; }
            set { SetPropertyValue<string>(nameof(Canal), ref fCanal, value); }
        }
        string fDerivadoA;
        public string DerivadoA
        {
            get { return fDerivadoA; }
            set { SetPropertyValue<string>(nameof(DerivadoA), ref fDerivadoA, value); }
        }
    }

}
